cc_binary(
    name = "server367",
    srcs = glob(["src/*", "main/*"]),
    deps = [],
)

cc_test(
    name = "server367-test",
    srcs = glob(["src/*", "test/*"], exclude=["src/main.cc"]),
    deps = [],
)
